# Terminal colours — Thrifted Rug (base24), applied as OSC escape sequences.
# The script is generated by shared/theme/apply-theme.sh; absent until you run it.
_base24=~/.cache/tinted-templates/tinted-shell/scripts/base24-thrifted-rug.sh
[ -f "$_base24" ] && . "$_base24"
unset _base24
